# -------- STAGE 1: Build --------
FROM golang:1.22-alpine AS builder

WORKDIR /app

# Copy go.mod and go.sum to the workspace
COPY go.mod go.sum ./
RUN go mod download

# Copy the entire source code to the workspace
COPY . .

# Build the Go application
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \ 
    go build -o order-service ./cmd/order-service

# -------- STAGE 2: Runtime --------
FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/order-service .

EXPOSE 50051
EXPOSE 8081

CMD ["./order-service"]